# Generated by Django 4.0 on 2025-10-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='decription',
            new_name='description',
        ),
    ]
