# Generated by Django 4.0 on 2025-10-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_', '0002_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commentaire',
            field=models.TextField(blank=True, default=True, max_length=1000),
        ),
    ]
